"""add avg_buy_price to user_stocks

Revision ID: 140287049419
Revises: 6add15cd7159
Create Date: 2025-11-09 12:16:25.055258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140287049419'
down_revision: Union[str, Sequence[str], None] = '6add15cd7159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stocks', sa.Column('avg_buy_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stocks', 'avg_buy_price')
    # ### end Alembic commands ###
