"""Added Transanctions Table

Revision ID: 6c73067a0c5b
Revises: 140287049419
Create Date: 2025-11-11 08:52:25.106349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c73067a0c5b'
down_revision: Union[str, Sequence[str], None] = '140287049419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_transanctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('stock', sa.Float(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('activity', sa.Enum('buy', 'sell', name='activity'), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_transanctions_id'), 'user_transanctions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_transanctions_id'), table_name='user_transanctions')
    op.drop_table('user_transanctions')
    # ### end Alembic commands ###
